import {Account, Period, TooltipData} from "@/commons/interfaces";

export const accounts: Account[] = [
    {
        id: 1,
        name: 'S1SEP2586479132',
        status: 'active',
        accountBalance: {
            currentBalance: "$145,166.78",
            currentEquity: "$145,166.78",
            high: "$150,000",
            low: "$145,166.78",
            weeklyNetPnL: "$0",
            bestDayPercentage: "-",
            bestDay: "-$73.40",
            worstDay: "-$4,524.54",
            avgWinningDay: "-",
            avgLosingDay: "-$1,610.74"
        }
    },
    {
        id: 2,
        name: 'SHYE36496NCHG33',
        status: 'inactive',
        accountBalance: {
            currentBalance: "$143,166.78",
            currentEquity: "$143,166.78",
            high: "$150,000",
            low: "$145,166.78",
            weeklyNetPnL: "$0",
            bestDayPercentage: "-",
            bestDay: "-$73.40",
            worstDay: "-$4,524.54",
            avgWinningDay: "-",
            avgLosingDay: "-$2,610.74"
        }
    },
    {
        id: 3,
        name: 'NJHA810003BGW33',
        status: 'breach',
        accountBalance: {
            currentBalance: "$143,166.78",
            currentEquity: "$143,166.78",
            high: "$150,000",
            low: "$145,166.78",
            weeklyNetPnL: "$0",
            bestDayPercentage: "-",
            bestDay: "-$73.40",
            worstDay: "-$4,524.54",
            avgWinningDay: "-",
            avgLosingDay: "-$2,610.74"
        }
    },
];

export const credentials = {
    login: 'pGd031d@hkh&Z~r1',
    password: 'pGd031d@hkh&Z~r1'
}

export const periods: Period[] = [
    {id: 'last_10_days', text: 'LAST 10 DAYS'},
    {id: 'last_30_days', text: 'LAST 30 DAYS'},
    {id: 'last_60_days', text: 'LAST 60 DAYS'},
]

export const tooltipData: TooltipData = {
    parameters: {
        startingBalance: "$50,000",
        maxPositionSize: "5",
        maxDrawdown: "$2,000",
    },
    accountDetails: {
        accountNumber: "9008713",
        platform: "Megatrader",
        username: "johndoe",
        password: "Same as your Megatrader account password",
    },
};

export const journalData = [
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 1
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 2
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 3
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 4
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 5
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 6
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 7
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 8
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 9
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 10
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 11
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 12
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 13
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 14
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 15
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 16
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 17
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 18
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 19
    },
    {
        "canEdit": true,
        "date": "Sep 27",
        "netPnl": "-$234.28",
        "pnlHigh": "$6.90",
        "pnlLow": "-$240.78",
        "totalContracts": 158.0,
        "totalFeesComm": "$139.28",
        "totalTrades": 22.0,
        "avgWinningTrades": "$28.07",
        "avgLosingTrades": "$22.04",
        "winningTradePercentage": 22.73,
        "maxConsecutiveWLTrades": "2\/12",
        "avgWLDuration": "00:05:05",
        "id": 20
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 21
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 22
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 23
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 24
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 25
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 26
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 27
    },
    {
        "canEdit": false,
        "date": "Average",
        "netPnl": "-$1,610.74",
        "pnlHigh": "$112.29",
        "pnlLow": "-$1,612.91",
        "totalContracts": 170.67,
        "totalFeesComm": "$186.91",
        "totalTrades": 12.67,
        "avgWinningTrades": "$137.37",
        "avgLosingTrades": "$209.26",
        "winningTradePercentage": 29.8,
        "maxConsecutiveWLTrades": "2\/6",
        "avgWLDuration": "00:06:09",
        "id": 28
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 29
    },
    {
        "canEdit": true,
        "date": "Sep 30",
        "netPnl": "-$73.40",
        "pnlHigh": "-$1",
        "pnlLow": "-$73.40",
        "totalContracts": 70.0,
        "totalFeesComm": "$25.90",
        "totalTrades": 4.0,
        "avgWinningTrades": "$2.60",
        "avgLosingTrades": "$39.90",
        "winningTradePercentage": 50.0,
        "maxConsecutiveWLTrades": "2\/1",
        "avgWLDuration": "00:05:05",
        "id": 30
    }
]